# Generated by Django 4.2.9 on 2024-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('roll', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
