# Generated by Django 4.2.9 on 2024-02-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=30)),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
