# Generated by Django 4.2.9 on 2024-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
