# Generated by Django 4.2.10 on 2024-02-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_mark_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(max_length=30),
        ),
    ]
